config/routes.rb
Shoplist::Application.routes.draw do
  match '/help',   to: 'home_pages#help'

  match '/about', to: 'home_pages#about'

  match '/contact', to: 'home_pages#contact'

  match '/home', to: 'home_pages#home'

  root :to => 'home_pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/home_pages/about.html.erb
<h1>HomePages#about</h1>
<p>Find me in app/views/home_pages/about.html.erb</p>

<%= link_to "Home", home_path %>
<%= link_to "Help", help_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>

app/views/home_pages/contact.html.erb
<h1>HomePages#contact</h1>
<p>Find me in app/views/home_pages/contact.html.erb</p>

<%= link_to "Home", home_path %>
<%= link_to "Help", help_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>

app/views/home_pages/help.html.erb
<h1>HomePages#help</h1>
<p>Find me in app/views/home_pages/help.html.erb</p>

<%= link_to "Home", home_path %>
<%= link_to "Help", help_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>

app/views/home_pages/home.html.erb
<h1>HomePages#home</h1>
<p>Find me in app/views/home_pages/home.html.erb</p>

<%= link_to "Home", home_path %>
<%= link_to "Help", help_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoplist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>